spring:

  # \u914D\u7F6Efreemarker
  freemarker:
    # \u8BBE\u7F6E\u6A21\u677F\u540E\u7F00\u540D
    suffix: .ftl
    # \u8BBE\u7F6E\u6587\u6863\u7C7B\u578B
    content-type: text/html
    # \u8BBE\u7F6E\u9875\u9762\u7F16\u7801\u683C\u5F0F
    charset: UTF-8
    # \u8BBE\u7F6E\u9875\u9762\u7F13\u5B58
    cache: false
    # \u8BBE\u7F6Eftl\u6587\u4EF6\u8DEF\u5F84
    template-loader-path:
      - classpath:/templates
  # \u8BBE\u7F6E\u9759\u6001\u6587\u4EF6\u8DEF\u5F84\uFF0Cjs,css\u7B49
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://192.168.0.10:3306/mybatis?useUnicode=true&characterEncoding=UTF-8
    username: pck
    password: Pck@*123
    driver-class-name: com.mysql.jdbc.Driver
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
  redis:
    database: 1
    host: 192.168.0.10
    port: 6379
    password: Pck@*123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000



