spring:
  datasource:
    url: jdbc:mysql://192.168.0.10:3306/mybatis?useUnicode=true&characterEncoding=UTF-8
    username: pck
    password: Pck@*123
    driver-class-name: com.mysql.jdbc.Driver
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000

  redis:
    database: 1
    host: 192.168.0.10
    port: 6379
    password: Pck@*123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

  cache:
    type: ehcache
    ehcache:
      config: classpath:app1_ehcache.xml




