###服务启动端口号
server:
  port: 8500
###服务名称(服务注册到eureka名称)  
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
  
spring:
  application:
    name:  app-goods
  redis:
    host: localhost
    port: 6379
  #  password: 123456
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
###数据库相关连接      
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop_goods?useUnicode=true&characterEncoding=UTF-
  data:
    elasticsearch:
    ####集群名称
     cluster-name: my-application
    ####地址 
     cluster-nodes: localhost:9300
  kafka:
    # kafka服务器地址(可以多个)
    bootstrap-servers: 192.168.212.252:9092
  