server:
  port: 8080


#app:
#  id: app-weixin

#apollo:
#  meta: http://www.dragon.com:30014
#  bootstrap:
#    enabled: true
#    namespaces: application,weixin,redis,mysql


base:
  dictionary:
    - 0                   #
    - 20                  #未使用的券总数量
    - 6                  #引流券可以再次领取的时间间隔，单位小时
    - 0                  #是否开启捧场券扫码地理位置校验
    - 60                  #分享达人分成比例
    - 10                  #业务员分享分成比例
    - 30                  #平台所留金额比例
    - 1                  #热门关键字开启标注，0-数据库查询，1-redis查询
    - 1                  #分销开通捧店金额
    - 2                  #直接开通捧店金额
    - 5                  #套餐支付时间，单位分钟
    - 20                  #捧店最大数量
    - 为庆贺您开通捧店，我们赠送的预约金是您在领取捧场套餐时可用来支付的，不可提现。捧场的分享  #开通捧店的提升
    - 100000                  #开通捧店送预约金金额
    - 10                  #每日点赞获取能量的最大次数
    - 0                  #小程序是否审核中，0-审核中，1-审核通过
    - 10000                  #新用户注册赠送的金额
    - 2000                  #邀请人获得的赠送
    - 25                  #捧达人分享获得金额，单位：%
    - 10                  #捧达人自用获得金额，单位：%
    - 10                  #捧店主自用获得金额，单位：%
    - 50                  #捧店主分享获得金额，单位：%
    - 10                  #捧店主上级获得金额，单位：%
    - 1575781199          #注册获得预约金截止日期

h5:
  share:
    urls:
      - space
      - https://h5.pengchangke.vip/h5_web/couponDetail.html?
      - https://h5.pengchangke.vip/h5_web/share.html?
      - https://h5.pengchangke.vip/h5_web/share.html?
      - http://marketing.pengchangke.vip/advertising/playbill.png
      - https://h5.pengchangke.vip/h5-share/couponDetail.html?
      - https://h5.pengchangke.vip/h5-share/share.html?
      - http://h5.pengchangke.vip/h5-share/add-shop.html?
      - http://h5.pengchangke.vip/h5-share/regist.html?
      - http://h5.pengchangke.vip/h5-share/mealRule.html
      - http://h5.pengchangke.vip/h5-share/courseList.html
      - http://h5.pengchangke.vip/h5-share/userTreaty.html
      - http://h5.pengchangke.vip/h5-share/pct-privacy.html














