server:
  port: 8080
dubbo:
  application:
    name: member-consumer
#  protocol:
#    name: dubbo
#    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 2000
#  scan:
#    base-packages: com.dragon.dubbo

