#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-portal-pay-web
    zipkin: 
      base-url: http://127.0.0.1:9411/
      ###全部采集  
    sleuth:
     sampler:
      probability: 1.0

#
#spring:
#  application:
#    name: app-itmayiedu-member


###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
server:
  port: 8050
  
redis:
 hostname: 127.0.0.1
 port: 6379
 password: 123456
 

xxl-sso:
  excluded:
    paths:
xxl:
  sso:
    server: http://xxlssoserver.com:8000/xxl-sso-server
    logout:
      path: /logout
    redis:
      address: redis://127.0.0.1:6379


